{% set name = "please" %}
{% set version = "17.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/thought-machine/please/archive/v{{ version }}.tar.gz
  sha256: 320d3fc66cbe77ea96ddda479c7fe920a638cf0a2de6b2bde63c4fed402937ce

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - plz --help

about:
  home: https://github.com/thought-machine/please
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: High-performance extensible build system for reproducible multi-language builds.
  dev_url: https://github.com/thought-machine/please

extra:
  recipe-maintainers:
    - danielnachun
