schema_version: 1

context:
  version: "17.31.0"

package:
  name: please
  version: ${{ version }}

source:
  url: https://github.com/thought-machine/please/archive/v${{ version }}.tar.gz
  sha256: cf74da63741d16385af00bef6a048672e85b3deede919223b44bcc3f2c8fdc52

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - plz --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: High-performance extensible build system for reproducible multi-language builds.
  homepage: https://github.com/thought-machine/please
  repository: https://github.com/thought-machine/please

extra:
  recipe-maintainers:
    - danielnachun
