schema_version: 1

context:
  version: "17.31.2"

package:
  name: please
  version: ${{ version }}

source:
  url: https://github.com/thought-machine/please/archive/v${{ version }}.tar.gz
  sha256: 480e9e1fe9246f93ac736a3cae28c9491956c11e4db0464d014ac0b819a783da

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - plz --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: High-performance extensible build system for reproducible multi-language builds.
  homepage: https://github.com/thought-machine/please
  repository: https://github.com/thought-machine/please

extra:
  recipe-maintainers:
    - danielnachun
