schema_version: 1

context:
  version: "17.29.1"

package:
  name: please
  version: ${{ version }}

source:
  url: https://github.com/thought-machine/please/archive/v${{ version }}.tar.gz
  sha256: 1a707de771c5907c8d38b65a922a9c2fddc6da46f5aad1e1b638bda928b49052

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - plz --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: High-performance extensible build system for reproducible multi-language builds.
  homepage: https://github.com/thought-machine/please
  repository: https://github.com/thought-machine/please

extra:
  recipe-maintainers:
    - danielnachun
